In [ ]:
import pandas as pd
from pathlib import Path


X_PATH = Path("../data_app/prepared/premier_league_next_matchday_features.csv")
F_PATH = Path("../data_app/prepared/premier_league_next_matchday_fixtures.csv")

X = pd.read_csv(X_PATH)
fx = pd.read_csv(F_PATH)

print("X shape:", X.shape)
print("Fixtures shape:", fx.shape)


nan_pct = (X.isna().mean() * 100).sort_values(ascending=False)
print("\n=== TOP NaN % w kolumnach ===")
print(nan_pct.head(20))


row_nan = X.isna().sum(axis=1)
out = fx.copy()
out["NaN_count"] = row_nan

print("\n=== Mecze z największą liczbą NaN ===")
display(out.sort_values("NaN_count", ascending=False).head(10))


idxs = out.sort_values("NaN_count", ascending=False).head(3).index.tolist()
for i in idxs:
    missing_cols = X.columns[X.iloc[i].isna()].tolist()
    print(f"\n--- MATCH index={i} ---")
    print(out.loc[i, ["Date","HomeTeam","AwayTeam","Matchday","League","NaN_count"]])
    print("Missing cols:", missing_cols)


key_cols = [c for c in X.columns if any(k in c for k in [
    "Home_GF_last5","Home_GA_last5","Home_Pts_last5",
    "Away_GF_last5","Away_GA_last5","Away_Pts_last5",
    "SeasonStrength_PtsDiff","FormDiff_"
])]
print("\n=== Kluczowe kolumny snapshotów i ich NaN count ===")
print(X[key_cols].isna().sum().sort_values(ascending=False).head(30))


print("\n=== Podgląd wartości snapshotów (pierwsze 5 meczów) ===")
display(pd.concat([fx.head(5), X[key_cols].head(5)], axis=1))

X shape: (10, 31)
Fixtures shape: (10, 8)

=== TOP NaN % w kolumnach ===
Home_GF_last5                 0.0
FormDiff_Pts_trend_3v10       0.0
Away_RecentFormIdx            0.0
Home_RecentFormIdx            0.0
FormDiff_GoalsShare_last5     0.0
FormDiff_AttDefRatio_last5    0.0
Away_GoalsShare_last5         0.0
Away_AttDefRatio_last5        0.0
Home_GoalsShare_last5         0.0
Home_AttDefRatio_last5        0.0
SeasonStrength_PtsDiff        0.0
Away_AvgPts_season            0.0
Home_AvgPts_season            0.0
Weekday                       0.0
Month                         0.0
FormDiff_Pts_last5            0.0
Home_GA_last5                 0.0
FormDiff_GD_last5             0.0
FormDiff_GA_last5             0.0
FormDiff_GF_last5             0.0
dtype: float64

=== Mecze z największą liczbą NaN ===

,Date,HomeTeam,AwayTeam,Matchday,League,Month,Weekday,IsWeekend,NaN_count
0,2025-12-26 20:00:00+00:00,Manchester United,Newcastle,18,premier_league,12,4,0,0
1,2025-12-27 12:30:00+00:00,Nott'm Forest,Manchester City,18,premier_league,12,5,1,0
2,2025-12-27 15:00:00+00:00,Arsenal,Brighton,18,premier_league,12,5,1,0
3,2025-12-27 15:00:00+00:00,Brentford,Bournemouth,18,premier_league,12,5,1,0
4,2025-12-27 15:00:00+00:00,Burnley,Everton,18,premier_league,12,5,1,0
5,2025-12-27 15:00:00+00:00,Liverpool,Wolverhampton,18,premier_league,12,5,1,0
6,2025-12-27 15:00:00+00:00,West Ham,Fulham,18,premier_league,12,5,1,0
7,2025-12-27 17:30:00+00:00,Chelsea,Aston Villa,18,premier_league,12,5,1,0
8,2025-12-28 14:00:00+00:00,Sunderland,Leeds,18,premier_league,12,6,1,0
9,2025-12-28 16:30:00+00:00,Crystal Palace,Tottenham,18,premier_league,12,6,1,0

--- MATCH index=0 ---
Date         2025-12-26 20:00:00+00:00
HomeTeam             Manchester United
AwayTeam                     Newcastle
Matchday                            18
League                  premier_league
NaN_count                            0
Name: 0, dtype: object
Missing cols: []

--- MATCH index=1 ---
Date         2025-12-27 12:30:00+00:00
HomeTeam                 Nott'm Forest
AwayTeam               Manchester City
Matchday                            18
League                  premier_league
NaN_count                            0
Name: 1, dtype: object
Missing cols: []

--- MATCH index=2 ---
Date         2025-12-27 15:00:00+00:00
HomeTeam                       Arsenal
AwayTeam                      Brighton
Matchday                            18
League                  premier_league
NaN_count                            0
Name: 2, dtype: object
Missing cols: []

=== Kluczowe kolumny snapshotów i ich NaN count ===
Home_GF_last5                 0
Home_GA_last5                 0
Home_Pts_last5                0
Away_GF_last5                 0
Away_GA_last5                 0
Away_Pts_last5                0
FormDiff_GF_last5             0
FormDiff_GA_last5             0
FormDiff_GD_last5             0
FormDiff_Pts_last5            0
FormDiff_Pts_trend_3v10       0
SeasonStrength_PtsDiff        0
FormDiff_AttDefRatio_last5    0
FormDiff_GoalsShare_last5     0
FormDiff_RecentFormIdx        0
dtype: int64

=== Podgląd wartości snapshotów (pierwsze 5 meczów) ===

,Date,HomeTeam,AwayTeam,Matchday,League,Month,Weekday,IsWeekend,Home_GF_last5,Home_GA_last5,...,Away_Pts_last5,FormDiff_GF_last5,FormDiff_GA_last5,FormDiff_GD_last5,FormDiff_Pts_last5,FormDiff_Pts_trend_3v10,SeasonStrength_PtsDiff,FormDiff_AttDefRatio_last5,FormDiff_GoalsShare_last5,FormDiff_RecentFormIdx
0,2025-12-26 20:00:00+00:00,Manchester United,Newcastle,18,premier_league,12,4,0,2.0,1.6,...,1.2,-0.6,-0.8,0.2,0.2,1.233333,0.250000,-0.103030,-0.011844,0.88
1,2025-12-27 12:30:00+00:00,Nott'm Forest,Manchester City,18,premier_league,12,5,1,1.6,1.6,...,1.8,-0.6,-0.2,-0.4,0.0,0.700000,-0.615385,-0.209091,-0.041714,0.00
2,2025-12-27 15:00:00+00:00,Arsenal,Brighton,18,premier_league,12,5,1,2.0,0.8,...,2.0,-0.2,0.4,-0.6,-0.6,1.000000,-0.583333,-0.202797,-0.099956,-0.24
3,2025-12-27 15:00:00+00:00,Brentford,Bournemouth,18,premier_league,12,5,1,1.8,1.4,...,1.0,-0.2,-1.4,1.2,0.6,0.333333,0.000000,0.229412,0.183190,0.44
4,2025-12-27 15:00:00+00:00,Burnley,Everton,18,premier_league,12,5,1,1.2,2.4,...,1.4,0.4,0.8,-0.4,-0.6,-1.766667,0.076923,0.027149,-0.016143,-1.24

In [4]:
import pandas as pd

preds = pd.read_csv("../data_app/predictions/all_leagues_next_matchday_predictions.csv")

print(preds["Pred"].value_counts(normalize=True))

Pred
H    0.666667
A    0.333333
Name: proportion, dtype: float64

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path


PROJECT_ROOT = Path.cwd().resolve().parents[0]  
print("PROJECT_ROOT:", PROJECT_ROOT)


HIST_PATH = PROJECT_ROOT / "data_app" / "processed" / "all_leagues" / "all_leagues_features.csv"
FEATURE_LIST_PATH = PROJECT_ROOT / "models" / "feature_list.json"


LEAGUE_KEY = "premier_league"
FUTURE_PATH = PROJECT_ROOT / "data_app" / "prepared" / f"{LEAGUE_KEY}_next_matchday_features.csv"
FIXTURES_PATH = PROJECT_ROOT / "data_app" / "prepared" / f"{LEAGUE_KEY}_next_matchday_fixtures.csv"

print("HIST_PATH exists:", HIST_PATH.exists(), HIST_PATH)
print("FUTURE_PATH exists:", FUTURE_PATH.exists(), FUTURE_PATH)
print("FIXTURES_PATH exists:", FIXTURES_PATH.exists(), FIXTURES_PATH)
print("FEATURE_LIST_PATH exists:", FEATURE_LIST_PATH.exists(), FEATURE_LIST_PATH)


hist = pd.read_csv(HIST_PATH, parse_dates=["Date"])
fixtures = pd.read_csv(FIXTURES_PATH, parse_dates=["Date"])
X_future = pd.read_csv(FUTURE_PATH)

feature_cols = pd.read_json(FEATURE_LIST_PATH, typ="series").tolist()


X_train = hist[feature_cols].copy()

missing_in_future = [c for c in feature_cols if c not in X_future.columns]
extra_in_future = [c for c in X_future.columns if c not in feature_cols]
print("\nMissing columns in X_future:", missing_in_future)
print("Extra columns in X_future:", extra_in_future)

X_future = X_future[feature_cols].copy()

def to_numeric_df(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    for c in out.columns:
        out[c] = pd.to_numeric(out[c], errors="coerce")
    return out

X_train_num = to_numeric_df(X_train)
X_future_num = to_numeric_df(X_future)


def describe_compare(train_s: pd.Series, future_s: pd.Series) -> dict:
    return {
        "train_nonnull": int(train_s.notna().sum()),
        "future_nonnull": int(future_s.notna().sum()),
        "train_mean": float(train_s.mean(skipna=True)),
        "future_mean": float(future_s.mean(skipna=True)),
        "train_std": float(train_s.std(skipna=True)),
        "future_std": float(future_s.std(skipna=True)),
        "train_p05": float(train_s.quantile(0.05)),
        "future_p05": float(future_s.quantile(0.05)),
        "train_p50": float(train_s.quantile(0.50)),
        "future_p50": float(future_s.quantile(0.50)),
        "train_p95": float(train_s.quantile(0.95)),
        "future_p95": float(future_s.quantile(0.95)),
    }

rows = []
for c in feature_cols:
    rows.append({"feature": c, **describe_compare(X_train_num[c], X_future_num[c])})

cmp = pd.DataFrame(rows)


cmp["future_unique"] = [X_future_num[c].nunique(dropna=True) for c in feature_cols]
cmp["future_nan_pct"] = (X_future_num.isna().mean() * 100).values


cmp_sorted = cmp.sort_values(
    by=["future_nan_pct", "future_unique", "future_std"],
    ascending=[False, True, True]
)

print("\n=== TOP 15 podejrzanych cech (future: dużo NaN / mało unikalnych / małe std) ===")
display(cmp_sorted.head(15))

print("\n=== szybki podgląd X_future (num) ===")
display(X_future_num.head(10))


row_nan = X_future_num.isna().sum(axis=1)
print("\nNaN per match row:")
print(row_nan.value_counts().sort_index())

print("\nFixtures preview:")
display(fixtures[["Date","HomeTeam","AwayTeam","Matchday","League"]].head(10))

PROJECT_ROOT: C:\Users\tdroz\OneDrive\Pulpit\Praca_Inzynierska\Praca
HIST_PATH exists: True C:\Users\tdroz\OneDrive\Pulpit\Praca_Inzynierska\Praca\data_app\processed\all_leagues\all_leagues_features.csv
FUTURE_PATH exists: True C:\Users\tdroz\OneDrive\Pulpit\Praca_Inzynierska\Praca\data_app\prepared\premier_league_next_matchday_features.csv
FIXTURES_PATH exists: True C:\Users\tdroz\OneDrive\Pulpit\Praca_Inzynierska\Praca\data_app\prepared\premier_league_next_matchday_fixtures.csv
FEATURE_LIST_PATH exists: True C:\Users\tdroz\OneDrive\Pulpit\Praca_Inzynierska\Praca\models\feature_list.json

Missing columns in X_future: []
Extra columns in X_future: []

=== TOP 15 podejrzanych cech (future: dużo NaN / mało unikalnych / małe std) ===

,feature,train_nonnull,future_nonnull,train_mean,future_mean,train_std,future_std,train_p05,future_p05,train_p50,future_p50,train_p95,future_p95,future_unique,future_nan_pct
0,Prob_H_b365,20477,0,0.442363,NaN,0.184357,NaN,0.146317,NaN,0.431766,NaN,0.775579,NaN,0,100.0
18,Month,20483,10,6.530440,12.000000,3.792976,0.000000,1.000000,12.000000,6.000000,12.000000,12.000000,12.000000,1,0.0
19,Weekday,20483,10,4.728751,5.100000,1.601967,0.567646,1.000000,4.450000,5.000000,5.000000,6.000000,6.000000,3,0.0
1,Home_GF_last5,20409,10,1.367736,1.640000,0.669321,0.323866,0.400000,1.200000,1.200000,1.700000,2.600000,2.000000,5,0.0
7,Away_GF_last5,20390,10,1.401054,1.300000,0.679202,0.492161,0.400000,0.580000,1.400000,1.400000,2.600000,1.910000,7,0.0
4,Home_Pts_last5,20409,10,1.354072,1.580000,0.687839,0.502881,0.200000,0.870000,1.400000,1.600000,2.600000,2.310000,7,0.0
2,Home_GA_last5,20409,10,1.396297,1.360000,0.619551,0.602218,0.400000,0.580000,1.400000,1.500000,2.500000,2.130000,7,0.0
3,Home_GD_last5,20409,10,-0.028561,0.280000,1.003209,0.806639,-1.600000,-0.930000,0.000000,0.400000,1.800000,1.420000,7,0.0
21,Away_AvgPts_season,19894,10,1.386004,1.320513,0.598322,0.506496,0.500000,0.504167,1.333333,1.384615,2.458333,1.888462,8,0.0
11,Away_Pts_last10,20390,10,1.386305,1.390000,0.569004,0.629727,0.500000,0.470000,1.333333,1.300000,2.400000,2.255000,8,0.0
15,FormDiff_GD_last5,20366,10,-0.064226,0.560000,1.404636,1.315886,-2.400000,-0.510000,0.000000,0.000000,2.200000,2.840000,8,0.0
25,Away_AttDefRatio_last5,20390,10,0.652692,0.541025,0.416376,0.284954,0.169928,0.173611,0.555556,0.485294,1.444444,0.959091,9,0.0
20,Home_AvgPts_season,19893,10,1.360072,1.472436,0.595322,0.475138,0.485714,0.835577,1.303030,1.599359,2.408081,2.131731,9,0.0
8,Away_GA_last5,20390,10,1.365247,1.660000,0.609144,0.653537,0.400000,0.780000,1.400000,1.700000,2.400000,2.510000,9,0.0
13,FormDiff_GF_last5,20366,10,-0.033477,0.240000,0.940084,0.658618,-1.600000,-0.600000,0.000000,0.300000,1.400000,1.220000,9,0.0

=== szybki podgląd X_future (num) ===

,Prob_H_b365,Home_GF_last5,Home_GA_last5,Home_GD_last5,Home_Pts_last5,Home_Pts_last10,Home_Pts_trend_3v10,Away_GF_last5,Away_GA_last5,Away_GD_last5,...,SeasonStrength_PtsDiff,Home_AttDefRatio_last5,Home_GoalsShare_last5,Away_AttDefRatio_last5,Away_GoalsShare_last5,FormDiff_AttDefRatio_last5,FormDiff_GoalsShare_last5,Home_RecentFormIdx,Away_RecentFormIdx,FormDiff_RecentFormIdx
0,NaN,2.0,1.6,0.4,1.6,1.7,-0.366667,1.4,2.0,-0.6,...,0.250000,0.769231,0.555401,0.466667,0.411644,-0.103030,-0.011844,1.44,1.08,0.88
1,NaN,1.6,1.6,0.0,1.4,0.8,1.533333,2.0,1.2,0.8,...,-0.615385,0.615385,0.499844,0.909091,0.624805,-0.209091,-0.041714,1.96,1.92,0.00
2,NaN,2.0,0.8,1.2,2.2,2.4,-0.733333,1.8,1.2,0.6,...,-0.583333,1.111111,0.714031,0.818182,0.599800,-0.202797,-0.099956,1.88,2.20,-0.24
3,NaN,1.8,1.4,0.4,1.8,1.3,-0.300000,1.6,2.4,-0.8,...,0.000000,0.750000,0.562324,0.470588,0.399900,0.229412,0.183190,1.32,0.60,0.44
4,NaN,1.2,2.4,-1.2,0.6,0.7,-0.700000,1.0,1.6,-0.6,...,0.076923,0.352941,0.333241,0.384615,0.384468,0.027149,-0.016143,0.24,1.76,-1.24
5,NaN,1.2,1.8,-0.6,1.2,1.2,-0.200000,0.4,2.6,-2.2,...,1.583333,0.428571,0.399867,0.111111,0.133289,0.888889,0.558753,1.08,0.00,2.16
6,NaN,1.8,1.8,0.0,1.4,1.1,1.233333,1.0,1.0,0.0,...,0.333333,0.642857,0.499861,0.500000,0.499750,0.000000,-0.062387,1.96,1.68,-1.16
7,NaN,2.0,0.4,1.6,2.4,1.9,1.100000,1.6,0.6,1.0,...,-0.153846,1.428571,0.832986,1.000000,0.726942,-0.100000,-0.084315,2.76,2.76,-0.56
8,NaN,1.4,1.0,0.4,1.6,1.6,-0.933333,0.8,2.2,-1.4,...,0.916667,0.700000,0.583090,0.250000,0.266578,0.750000,0.425464,1.04,0.24,1.68
9,NaN,1.4,0.8,0.6,1.6,1.8,0.533333,1.4,1.8,-0.4,...,0.000000,0.777778,0.636075,0.500000,0.437363,0.214286,0.088814,2.04,0.52,1.40

NaN per match row:
1    10
Name: count, dtype: int64

Fixtures preview:

,Date,HomeTeam,AwayTeam,Matchday,League
0,2025-12-26 20:00:00+00:00,Manchester United,Newcastle,18,premier_league
1,2025-12-27 12:30:00+00:00,Nott'm Forest,Manchester City,18,premier_league
2,2025-12-27 15:00:00+00:00,Arsenal,Brighton,18,premier_league
3,2025-12-27 15:00:00+00:00,Brentford,Bournemouth,18,premier_league
4,2025-12-27 15:00:00+00:00,Burnley,Everton,18,premier_league
5,2025-12-27 15:00:00+00:00,Liverpool,Wolverhampton,18,premier_league
6,2025-12-27 15:00:00+00:00,West Ham,Fulham,18,premier_league
7,2025-12-27 17:30:00+00:00,Chelsea,Aston Villa,18,premier_league
8,2025-12-28 14:00:00+00:00,Sunderland,Leeds,18,premier_league
9,2025-12-28 16:30:00+00:00,Crystal Palace,Tottenham,18,premier_league

In [ ]:
import joblib

MODEL_PATH = PROJECT_ROOT / "models" / "decision_tree_model.pkl"
ENC_PATH = PROJECT_ROOT / "models" / "label_encoder.pkl"

model = joblib.load(MODEL_PATH)
le = joblib.load(ENC_PATH)

print("Model loaded:", MODEL_PATH.exists())
print("Encoder loaded:", ENC_PATH.exists())
print("Classes (encoder):", le.classes_)


proba = model.predict_proba(X_future_num)
pred_idx = np.argmax(proba, axis=1)
pred_cls = le.inverse_transform(pred_idx)

proba_df = pd.DataFrame(proba, columns=[f"P_{c}" for c in le.classes_])
out = pd.concat(
    [fixtures[["Date","HomeTeam","AwayTeam","Matchday","League"]].reset_index(drop=True),
     proba_df,
     pd.Series(pred_cls, name="Pred")],
    axis=1
)

display(out)



print("Unique rows of proba:", pd.DataFrame(proba).round(6).drop_duplicates().shape[0], "/", proba.shape[0])
print(proba_df.std().sort_values())
print(pd.Series(pred_cls).value_counts(normalize=True))

Model loaded: True
Encoder loaded: True
Classes (encoder): ['A' 'D' 'H']

,Date,HomeTeam,AwayTeam,Matchday,League,P_A,P_D,P_H,Pred
0,2025-12-26 20:00:00+00:00,Manchester United,Newcastle,18,premier_league,0.245143,0.290835,0.464022,H
1,2025-12-27 12:30:00+00:00,Nott'm Forest,Manchester City,18,premier_league,0.247137,0.283834,0.469029,H
2,2025-12-27 15:00:00+00:00,Arsenal,Brighton,18,premier_league,0.247137,0.283834,0.469029,H
3,2025-12-27 15:00:00+00:00,Brentford,Bournemouth,18,premier_league,0.247137,0.283834,0.469029,H
4,2025-12-27 15:00:00+00:00,Burnley,Everton,18,premier_league,0.245143,0.290835,0.464022,H
5,2025-12-27 15:00:00+00:00,Liverpool,Wolverhampton,18,premier_league,0.245143,0.290835,0.464022,H
6,2025-12-27 15:00:00+00:00,West Ham,Fulham,18,premier_league,0.245143,0.290835,0.464022,H
7,2025-12-27 17:30:00+00:00,Chelsea,Aston Villa,18,premier_league,0.247137,0.283834,0.469029,H
8,2025-12-28 14:00:00+00:00,Sunderland,Leeds,18,premier_league,0.245143,0.290835,0.464022,H
9,2025-12-28 16:30:00+00:00,Crystal Palace,Tottenham,18,premier_league,0.245143,0.290835,0.464022,H

=== Czy wszystkie wiersze mają takie same proby? ===
Unique rows of proba: 2 / 10

=== Odchylenie standardowe prob po meczach (jeśli ~0, to model widzi wszystko tak samo) ===
P_A    0.001030
P_H    0.002586
P_D    0.003615
dtype: float64

=== Najczęstsza predykcja ===
H    1.0
Name: proportion, dtype: float64

In [8]:
import joblib
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path("..").resolve()

MODEL_PATH = PROJECT_ROOT / "models" / "decision_tree_model.pkl"
FEATURE_LIST_PATH = PROJECT_ROOT / "models" / "feature_list.json"

model = joblib.load(MODEL_PATH)
model.calibrated_classifiers_[0].estimator.named_steps

{'imputer': SimpleImputer(strategy='median'),
 'model': DecisionTreeClassifier(class_weight='balanced', criterion='entropy',
                        max_depth=4, min_samples_leaf=10, random_state=0)}

In [ ]:
import pandas as pd
import joblib
from pathlib import Path

PROJECT_ROOT = Path(r"C:\Users\tdroz\OneDrive\Pulpit\Praca_Inzynierska\Praca")

MODEL_PATH = PROJECT_ROOT / "models" / "decision_tree_model.pkl"
FEATURE_LIST_PATH = PROJECT_ROOT / "models" / "feature_list.json"

model = joblib.load(MODEL_PATH)


tree = model.calibrated_classifiers_[0].estimator.named_steps["model"]

feature_names = pd.read_json(FEATURE_LIST_PATH, typ="series").tolist()

fi = (
    pd.DataFrame({
        "feature": feature_names,
        "importance": tree.feature_importances_
    })
    .sort_values("importance", ascending=False)
)

fi.head(15)

                       feature  importance
21      SeasonStrength_PtsDiff    0.836580
4              Home_Pts_last10    0.036304
17                       Month    0.032242
10             Away_Pts_last10    0.026496
14           FormDiff_GD_last5    0.025841
26  FormDiff_AttDefRatio_last5    0.020740
8                Away_GD_last5    0.012570
12           FormDiff_GF_last5    0.009225
23       Home_GoalsShare_last5    0.000000
20          Away_AvgPts_season    0.000000
22      Home_AttDefRatio_last5    0.000000
0                Home_GF_last5    0.000000
19          Home_AvgPts_season    0.000000
25       Away_GoalsShare_last5    0.000000
27   FormDiff_GoalsShare_last5    0.000000